export const FIRST_RELEASE_YEAR = 1970
export const LAST_RELEASE_YEAR = new Date().getFullYear()
export const AMOUNT_OF_YEARS = LAST_RELEASE_YEAR + 1 - FIRST_RELEASE_YEAR
export const RELEASE_YEARS = [...Array(AMOUNT_OF_YEARS).keys()]
  .map(value => value + FIRST_RELEASE_YEAR)
  .reverse()
export const MOVIE_SORTINGS = [
  'POPULARITY_DESC',
  'POPULARITY_ASC',
  'RELEASE_DATE_ASC',
  'RELEASE_DATE_DESC',
  'REVENUE_ASC',
  'REVENUE_DESC',
  'PRIMARY_RELEASE_DATE_ASC',
  'PRIMARY_RELEASE_DATE_DESC',
  'ORIGINAL_TITLE_ASC',
  'ORIGINAL_TITLE_DESC',
  'VOTE_AVERAGE_ASC',
  'VOTE_AVERAGE_DESC',
  'VOTE_COUNT_ASC',
  'VOTE_COUNT_DESC',
]
